### PR TITLE
0.3.1.14

### PR DESCRIPTION
**Pull request by enricogior**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/jxcore/114)

### CODE REVIEW

**Comment by yaronyg** [comment]
@enricogior Please see my comments. I'm making the assumption that skipped tests that don't work when embedded mean we don't run those tests at least on iOS. Some of the tests I saw skipped, especially around basic HTTP functionality and TLS were kind of concerning. Do we have equivalent tests elsewhere to make sure they work on iOS and Android?

---

Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 139 of 139 files at r3, 6 of 6 files at r4, 5 of 7 files at r5, 4 of 10 files at r6, 8 of 10 files at r7, 2 of 4 files at r8, 2 of 2 files at r9, 8 of 8 files at r10.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/simple/test-http-304.js, line 21 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKN2pE9VChJD0pX-Fd:-KsKN2pE9VChJD0pX-Fe:b-ftn27b) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-http-304.js#L21)):*
> ```JavaScript
> 
> var s = http.createServer(function(request, response) {
>   response.writeHead(304);
> ```

Do we have an equivalent test for this that does run embedded? Seems like a fairly important thing to test.

---

*[test/simple/test-http-full-response.js, line 4 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKNSiZ7XjNSWPCubmJ:-KsKNSi_eqplu8z7z_6G:b-vduatw) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-http-full-response.js#L4)):*
> ```JavaScript
> 
> if(process.isEmbedded === true) {
>   console.error('Skipping: the test works only in standalone mode');
> ```

Why does this test not work? I know it's using child_process but is that completely banned in stand alone mode?

---

*[test/simple/test-https-simple.js, line 3 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKNkELN6w_Ua__QXXE:-KsKNkELN6w_Ua__QXXF:bai0hym) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-https-simple.js#L3)):*
> ```JavaScript
> // Copyright & License details are available under JXCORE_LICENSE file
> if(process.isEmbedded === true) {
>   console.error('Skipping: the test works only in standalone mode');
> ```

Do we have the equivalent of this somewhere else that does run in embedded mode?

---

*[test/simple/test-tls-psk-client.js, line 2 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKOOvadFecr5mfgbH7:-KsKOOvbv4VjH7f1A8Hd:b1hf61r) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-psk-client.js#L2)):*
> ```JavaScript
> // Copyright & License details are available under JXCORE_LICENSE file
> if(process.isEmbedded === true) {
> ```

Wait, doesn't this test the PSK feature that we introduced? Don't we need a version that works?

---

*[test/simple/test-tls-psk-server.js, line 12 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKOVP7og5dJ_RBdQI1:-KsKOVP7og5dJ_RBdQI2:b-289b99) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-psk-server.js#L12)):*
> ```JavaScript
>   process.exit(0);
> }
> if(process.isEmbedded === true) {
> ```

Same comment as on test-tls-psk-client.js

---

*[test/simple/test-tls-securepair-client.js, line 10 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKObThfsqHiSSl6gZ1:-KsKObThfsqHiSSl6gZ2:bswdodw) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-securepair-client.js#L10)):*
> ```JavaScript
> var join = require('path').join;
> var net = require('net');
> var assert = require('assert');
> ```

Does this mean that basically we just aren't testing basic TLS functionality any more? At least on iOS?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-:-KsKOscoEsAt9TCLi0CX:b-b2s1bt)*

**Comment by enricogior** [comment]
*[test/simple/test-http-304.js, line 21 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKN2pE9VChJD0pX-Fd:-KsNGaflBq77HBiX-gPx:b-814nh0) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-http-304.js#L21)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Do we have an equivalent test for this that does run embedded? Seems like a fairly important thing to test.
</blockquote></details>

Some of these tests don't really need to be run on all platforms, in the sense that if they pass on mac OS there is really nothing that is platform dependent and can cause them to fail on iOS or Android.
Sure, it would be better to run all the possible tests on all platforms, but given the resource we add, we didn't have the time do rewrite all the skipped tests. Also, consider that before we created the test app for iOS, we weren't testing iOS at all, since running jxcore standalone on a jailbroken device mean basically nothing. With the test app on non-jailbroken devices we were able to run hundreds of tests that have never been run before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
*[test/simple/test-http-full-response.js, line 4 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKNSiZ7XjNSWPCubmJ:-KsNJNPmgzV-wjymdjpn:bl8s7l7) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-http-full-response.js#L4)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why does this test not work? I know it's using child_process but is that completely banned in stand alone mode?
</blockquote></details>

In some tests the child_process is not the only problem. The problem is that they execute external binaries such 'curl' or in this case 'ab'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
*[test/simple/test-https-simple.js, line 3 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKNkELN6w_Ua__QXXE:-KsNKOQdte9b4wsUyC1d:b-e5t72i) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-https-simple.js#L3)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Do we have the equivalent of this somewhere else that does run in embedded mode?
</blockquote></details>

This is another test that uses 'curl'. We run several other https tests that don't use external tools for validation and test https using jxcore for both client and server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
*[test/simple/test-tls-psk-client.js, line 2 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKOOvadFecr5mfgbH7:-KsNMMWaysvZDAWt2Iae:b-95sg6j) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-psk-client.js#L2)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Wait, doesn't this test the PSK feature that we introduced? Don't we need a version that works?
</blockquote></details>

There are 7 tests for the psk functionality, we run 5 of them, and skip two that cannot be run on mobile because they use external executables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
*[test/simple/test-tls-psk-server.js, line 12 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKOVP7og5dJ_RBdQI1:-KsNMmmEyi2BXLHGGrd0:b4yaad) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-psk-server.js#L12)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Same comment as on test-tls-psk-client.js
</blockquote></details>

There are 7 tests for the psk functionality, we run 5 of them, and skip two that cannot be run on mobile because they use external executables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
*[test/simple/test-tls-securepair-client.js, line 10 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKObThfsqHiSSl6gZ1:-KsNMrubmBoLxWXknQjl:b-snq3gp) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-tls-securepair-client.js#L10)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Does this mean that basically we just aren't testing basic TLS functionality any more? At least on iOS?
</blockquote></details>

No, some tls tests are skipped on mobile, but there are several others (~50) that test tls in different ways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114)*

**Comment by enricogior** [comment]
We run more than 500 tests on iOS. The skipped tests use external executables. That doesn't mean we don't test those functionalities at all, it means we don't test those using external "validation" but only using "self" validation (both client and server are implemented by jxcore itself).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-:-KsNNidXJrWZWh-AQDQU:b-x1q6nr)*

**Comment by yaronyg** [comment]
Sigh... I'm not going to pretend to be happy and I genuinely do get your point about us running the tests on desktop and that nothing should (famous last words) be different in mobile. I also understand that there are other tests that do run on mobile that cover some of the areas on the tests. And also your point that before we basically didn't run any real tests on iOS at all so obviously we are in a better place. And most importantly I understand that we have limited time and resources. So the real reason for this long note is to make myself feel better about saying :lgtm:. We have to work with the world we have. :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/simple/test-http-304.js, line 21 at r10](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-KsKN2pE9VChJD0pX-Fd:-KsOu61u_4INUIskbyMh:b30i1gj) ([raw file](https://github.com/thaliproject/jxcore/blob/5d2fb4a12a9525f897a3e3923e89cb4ff5d7ba47/test/simple/test-http-304.js#L21)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Some of these tests don't really need to be run on all platforms, in the sense that if they pass on mac OS there is really nothing that is platform dependent and can cause them to fail on iOS or Android.
Sure, it would be better to run all the possible tests on all platforms, but given the resource we add, we didn't have the time do rewrite all the skipped tests. Also, consider that before we created the test app for iOS, we weren't testing iOS at all, since running jxcore standalone on a jailbroken device mean basically nothing. With the test app on non-jailbroken devices we were able to run hundreds of tests that have never been run before.
</blockquote></details>

Not ideal but what is? Understood and agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-:-KsOuNFmptalZsjofXMy:b-ndzplc)*

**Comment by enricogior** [comment]
Agree.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/jxcore/114#-:-Ksc1DY6x4I6w8Egmtvr:bqog7zb)*

**Pull request merged**
